### PR TITLE
Commonjs build

### PR DESCRIPTION
**Pull request by ljacho**

### CODE REVIEW

**Comment by erikmeliska** [comment]
somebody to review?

**Comment by cohitre** [comment]
This functionality should already be in the published packages.

**Comment by ljacho** [comment]
> This functionality is already be in the published packages. Is it not working for you as currently published?

it's not as there are error messages about `import` & `export` statements

**Comment by cohitre** [comment]
Version 0.0.5 of `@usewaypoint/email-builder` should include the commonjs exports.

**Comment by cohitre** [comment]
Test project here: https://github.com/usewaypoint/email-builder-common-js-playground

**Pull request closed without merging**
